# Generated by Django 4.2.18 on 2025-01-26 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_first_name', models.CharField(max_length=50)),
                ('p_last_name', models.CharField(max_length=50)),
                ('p_dob', models.DateField()),
                ('p_email', models.EmailField(max_length=254, unique=True)),
                ('history_afib', models.BooleanField(default=False, help_text='Depiction of patient having history of Atrial Fibrillation')),
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('glucose', models.FloatField()),
                ('bun', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('egfr', models.FloatField()),
                ('test_date', models.DateField()),
                ('test_creation_date', models.DateTimeField(auto_now_add=True)),
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='fhPortal.patient')),
            ],
        ),
    ]
